config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :edit, :update]
  resources :posts, only: [:new, :show, :create, :destroy]

  get 'search' => 'search#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hash_tag.rb
class HashTag < ApplicationRecord
  has_many :post_hash_tags
  has_many :posts , through: :post_hash_tags
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :post_hash_tags
  has_many :hash_tags , through: :post_hash_tags

  has_one_attached :image
  validate :image_presence

  after_commit :create_hash_tags, on: :create

  def image_presence
    errors.add(:image, "can't be blank ! ") unless image.attached?
  end

  def extract_name_hash_tags
    description.to_s.scan(/#\w+/).map{|name| name.gsub("#", "")}
  end

  def create_hash_tags
    extract_name_hash_tags.each do |name|
      hash_tags.create(name: name)
    end
  end

  
end

app/models/post_hash_tag.rb
class PostHashTag < ApplicationRecord
  belongs_to :post
  belongs_to :hash_tag
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_one_attached :avatar
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def show
    @posts = Post.find(prams[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.order(created_at: :desc).page(params[:page]).per(5)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    Post.create(post_params)
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:description, :image, :user_id)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
    if params[:query].start_with?('#')
      query  = params[:query].gsub('#', '')
      @posts = Post.joins(:hash_tags).where(hash_tags: {name:    query})
    else
      @posts = Post.where("description like ?", "%#{params[:query]}%")
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user , only: [:show]

  def show
    @posts = @user.posts.order(created_at: :desc)
  end

  def edit
  end

  def update
    current_user.update(user_params)
    redirect_to current_user
  end

private

  def user_params
    params.require(:user).permit(:username, :name, :website, :bio, :email, :phone, :gender, :avatar)
  end

  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="posts">
  <% @posts.each do |post| %>
    <section class="post">
      <div class="user">
        <div class="avatar">
          <% if post.user.avatar.attached? %>
            <%= link_to  user_path(post.user) do%>
              <%= image_tag(post.user.avatar, :alt => "user avatar", class: 'avatar') %>
            <% end %>
          <% end %>
        </div>
        <div class="username">
          <%= link_to post.user.username, user_path(post.user) %>
        </div>
      </div>
      <%= image_tag post.image, class: 'main-image' %>
      <div class="description">
        <% post.description.to_s.split(' ').each do |word| %>
          <% if word.start_with?('#') %>
            <%= link_to word, search_path(query: word) %>
          <%else %>
            <%= word %>
          <%end %>
        <% end %>
      </div>
    </section>
  <% end %>
  <%= paginate @posts %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--Navigation Bar-->
    <nav class="navbar navbar-light bg-light d-flex">
      <div class="container">
        <div class="logo">
          <%= link_to root_url, class: "navbar-brand" do%>
            <%= fa_stacked_icon "camera inverse", base: "circle"%>
            Instagram
          <% end %>
        </div>
        <div class="m-auto">
          <%= form_with url: search_path, method: :get, local: true, class: 'form-inline search-form' do |form| %>
            <%= form.text_field :query, value: params[:query], class: 'form-control mr-sm-2', placeholder: '#search' %>
          <% end %>
        </div>
        <div class="user-section">
          <a><i class="fa fa-compass"></i></a>
          <a><i class="fa fa-heart"></i></a>
          <% if user_signed_in? %>
            <a href="<%= user_path(current_user)%>">
              <i class="fa fa-user"></i>
            </a>
          <% else %>
            <a href="<%= new_user_session_path%>">
              <i class="fa fa-sign-in"></i>
            </a>
          <% end %>
        </div>
      </div>
    </nav>

    <!--Main content-->
    <main class="container" style="min-height: 500px;">
      <%= yield %>
    </main>

    <!--Footer-->
    <footer class="container footer">
      <nav class="navbar d-flex">
        <ul>
          <li>ABOUT US
          </li>
          <li>SUPPORT</li>
          <li>PRESS</li>
          <li>API</li>
          <li>JOBS</li>
          <li>PRIVACY</li>
          <li>TERMS</li>
          <li>DIRECTORY</li>
          <li>PROFILES</li>
          <li>HASHTAGS</li>
          <li>LANGUAGE</li>
        </ul>
        <p> © 2018 INSTAGRAM </p>
      </nav>
    </footer>
  </body>
</html>

app/views/posts/new.html.erb
<%= form_for Post.new do |f| %>
  <div class="form-group">
    <%= f.text_field :description %>
  </div>
  <div class="form-group">
    <%= f.file_field :image %>
  </div>
  <div class="form-group">
    <%= f.text_field :user_id, value: current_user.id, class:'d-none'%>
  </div>
  <br>
  <div class="text-center">
    <%= f.submit 'Create Post', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/show.html.erb
<div class="post-show row">
  <div class="col-md-8">
    <%= image_tag @post.image, class: 'image' %>
  </div>
  <div class="col-md-4">
    <div class="user">
      <div class="avatar">
        <% if @post.user.avatar.attached? %>
          <%= link_to user_path(@post.user) do %>
            <%= image_tag @post.user.avatar %>
          <% end %>
        <% end %>
      </div>
      <%= link_to @post.user.name, user_path(@post.user), class: 'username' %>
    </div>
    <div class="description">
      <% post.description.to_s.split(' ').each do |word| %>
        <% if word.start_with?('#') %>
          <%= link_to word, search_path(query: word) %>
        <%else %>
          <%= word %>
        <%end %>
      <% end %>
    </div>
    <div class="delete">
      <% if current_user.posts.exists?(@post.id) %>
        <%= link_to 'Remove', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </div>
  </div>
</div>

app/views/search/index.html.erb
<div class="search-page">
  <% if @posts.exists? %>
    <h1>Top Posts</h1>
  <% else %>
    <h1>Oop! No matching posts ...</h1>
  <% end %>
<div class="user-images">
    <% @posts.each do |post|%>
      <div class="wrapper">
        <%=image_tag post.image %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with model: current_user, local: true, html: {class: "form-horizontal form-edit-user"} do |f| %>
  <div class="form-group row">
    <div class="col-sm-3 col-form-label" >
      <% if current_user.avatar.attached? %>
        <%= image_tag current_user.avatar, class: 'avatar'%>
      <% end %>
    </div>
    <div class="col-sm-9">
      <p class="username"><%=current_user.username %></p>
      <%= f.file_field :avatar, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :name, class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :username, class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.text_field :username, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :website, class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.text_field :website, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :bio, class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.text_area :bio, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :email, class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.text_field :email, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :phone, class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.text_field :phone, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :gender, class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.text_field :gender, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-3">
    </div>
    <div class="col-sm-9">
      <%= f.submit "Submit", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="user-edit-page">
  <div class="actions">
    <div class="nav flex-column nav-pills" role="tablist" aria-orientation="vertical">
      <a class="nav-link active" data-toggle="pill" href="#v-pills-home" role="tab" aria-selected="true">Edit Profile</a>
      <a class="nav-link" data-toggle="pill">Change Password</a>
      <a class="nav-link" data-toggle="pill">Authorized Applications</a>
      <a class="nav-link" data-toggle="pill">Email and SMS</a>
      <a class="nav-link" data-toggle="pill">Manage Contacts</a>
      <a class="nav-link" data-toggle="pill">Privacy and Security</a>
    </div>
  </div>
  <div class="details tab-content">
    <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
      <!-- Form edit profile -->
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-profile">
  <div class="profile row">
    <div class="col-md-4 avatar">
      <div class="wrapper">
        <% if current_user.avatar.attached? %>
          <%= image_tag @user.avatar %>
        <% end %>
      </div>
    </div>

    <div class="col-md-8 basic-info">
      <div class="user-wrapper">
        <h2 class="username"><%= @user.username %></h2>
        <a class="edit-profile" href="<%= edit_user_path(current_user) %>" >
          <button>Edit Profile</button>
        </a>
      </div>
      <ul class="posts">
        <li><span><%= @posts.count %></span> posts</li>
        <li><span>195</span> followers</li>
        <li><span>345</span> following</li>
      </ul>
      <h2 class="name"><%= @user.name %></h2>
      <a class="website"><%= @user.website %></a>
    </div>
  </div>
</div>

<div class="user-tabs">
  <a class="tab active" href="">
    <i class="fa fa-th"></i>
    POSTS
  </a>
  <a class="tab" href="">
    <i class="fa fa-tv"></i>
    IGTV
  </a>
  <a class="tab" href="">
    <i class="fa fa-bookmark"></i>
    SAVED
  </a>
  <a class="tab" href="">
    <i class="fa fa-tag"></i>
    TAGGED
  </a>
</div>

<div class="user-images">
  <% @posts.each do |post|%>
    <div class="wrapper">
      <%=image_tag post.image %>
    </div>
  <% end %>
</div>